# Generated by Django 4.2 on 2023-05-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raspisanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, verbose_name='Название')),
                ('time', models.DateTimeField(verbose_name='Время')),
                ('zaniatia', models.TextField(verbose_name='Занятия')),
            ],
        ),
    ]
